spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Mobodra?serverTimezone=Asia/Seoul
    username: root
    password: 28tkeks**
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    ddl-auto: update
  h2:
    console:
      enabled: false
    path: /console
  devtools:
    livereload:
      enabled: true
  security:
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: false
        same-site: none